Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -17,13 +17,27 @@ jobs:
         with:
           python-version: "3.12"
 
-      - run: |
+      - name: Install dependencies
+        run: |
           pip install -e ./irispie-package
           pip install pytest
 
-      - run: |
+      - name: Run tests
+        run: |
           cd $GITHUB_WORKSPACE/irispie-package
           pytest ./tests/series -ra > ./tests/report.txt
+
+      - name: Bump version
+        if: ${{ success() }}
+        run: |
+          if ! [[ -e .bump_type ]]; then
+            echo "Cannot release without .bump_type"
+            exit 1
+          fi
+          BUMP_TYPE=$(< .bump_type)
+          python ./irispie-package/scripts/bump_version.py \
+            --bump_type=$BUMP_TYPE \
+            --source_path=./irispie-package/pyproject.toml
 
       - name: When passed
         if: ${{ success() }}
@@ -33,7 +47,7 @@ jobs:
           echo "${{ secrets.IRISPIE_SERVICE_TOKEN }}"
           git config --local user.email "jaromir.benes@gmail.com"
           git config --local user.name "Jaromir Benes"
-          if [[ $(git ls-remote --heads github */test) ]]; then
+          if [[ $(git ls-remote --heads origin */test) ]]; then
             git push origin --delete test
           fi
           git switch -c test
